project:
  type: book
  output-dir: docs

book:
  title: "南极谋杀案"
  author: "MY"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: ctexbook
    latex-engine: xelatex
    mainfont: "Heiti SC"

lang: zh
editor: visual

