# 南极谋杀案 {.unnumbered}

《南极战争法》签署后十年的2087年，无人战场上出现一具人类死尸，围绕这具不应该出现的尸体，战争代理商、人类调查团及世界联合政府展开了多方博弈，故事将通过不同参与者的对话、日志或备忘展开，读者需自行拼凑出“真相”。

# 无人战争

“情况就是这么个情况，咋办？”

“额，按说那边不应该有活人啊？”

“现实情况也没出现活人啊，只是出现了个死人而已。”

“确认身份了吗？”

“嗯，是个欧洲人，生理年龄73岁，社会寄生虫，无足轻重的那种”

“死因确认是机器人，不是意外？”

“不是意外，是YM-7型战争机器人，新闻稿里说锁定目标后投掷的炸弹”

“关键人咋过去的？”

“不知道”

“大哥，你好歹调查清楚点，《南极战争法》签了十年了，《无人战争增补条例》也执行三年了，现在突然死了人，这是要搞出大事的节奏”

“我有啥办法，战场设监控就是个笑话，按法律那边就算打出外星人都不负责任的”

“公司那边咋说？”

“公司说抓紧找出凶手，后面已经堆积了六十几场战役了”

“这次是因为啥打的？”

“加州跟德州呗，一年打五六次，这次是德州赢了，按合同南加州有块地就归德州了”

“他们对死人有什么看法”

“表示遗憾”

“死者家属呢？”

“这是个绝户，本来就是孤儿”

“那要不就算了？”

“咋可能，无人战争死了人，公司要被起诉的，再说欧洲那边都已经知道了”

“也对，就算是寄生虫死了也一定早就传遍世界了，信息熵太高了”

“《南极战争法》第二十二条如何？”

“‘战争造成的第三方死伤视为民事行为，不负刑事责任，但受害方可追究双方民事赔偿’ 这条是一定会生效的，我担心的是《无人战争增补条例》，第十三条写得很清楚，‘因战争代理商过失造成的损失，交战方免责，需追究战争代理商责任，严重时取消代理资格并追究相关刑事与民事责任。’”

“我们甩锅给战争机器人故障？这玩意是交战双方自行购买的，跟我们没关？”

“老大，你忘了上周我们公司收购YM公司的事了？”

“啥？我不知道啊”

“上周三的事，结果这周五就死人了”

“会不会是其他竞争对手设计我们啊？”

“你是说EH公司？”

“这个很难证明的，还不如说那个人是自杀”

“对啊，我咋没想到，你又查不出咋来的，YM-7型又没有人类识别模块，有可能自杀啊”

“额，这事还真不好说，YM系列只是拿掉了人类识别模块，但最初设计是对人的，保留了一个枪口”

“枪？无人战争不都是用石墨弹、爆裂弹这种攻击机器的吗？咋还有枪呢？”

“虽然是装饰，但确实是能发子弹的枪，《南极战争法》最初也是说国家矛盾异地解决，所以才在南极划出战争区域让交战国签好胜负合同后开打，最初都是军队直接打的，当然需要枪”

“你不说是被炸死的吗？”

“新闻里是这样”

“啥意思？”

“其实是枪杀，YM-3型的子弹，适配7型的装饰用弹夹，但这次双方都用的一个型号战争机器人，我们这边也查不出来是哪一台，因为战后就剩了一台德州的还能动，也是靠这个判定的德州获胜，估计是送过来前特意加配的子弹”

“新闻稿哪来的？”

“系统生成的”

“算了，这事估计不是你我能处理的了，上报公司吧”

“估计要派人类调查团过来”

“来就来吧，另外公司送来一批好机油，过会分你点，这冰天雪地的，我们这老型号得学会爱护自己”

以上就是2087年南极谋杀案的序幕，而此案也是人类对地球失控的开端。

# 肢解快递

他拔下接口，对着空气问到：

“就是说我要重回南极？”

“是的，请履行您的地球公民义务。此外，请选择您的旅行方式，因为要求24小时内到，您可以选择肢解快递或代行者虚拟登陆”

“代行者”

“好的，这边给您推荐的是肢解快递，您只需要睡一觉，醒来就能到达”

“听不懂人话吗，我说虚拟登陆”

“您的脑机接口存在安全风险且但您与代行者同步率一直都不高，另外根据您的身体状况，医疗系统认为您的日均沉浸式体验过长”

“我不喜欢肢解快递，上次去南非就给我丢了一条胳膊”

“您可以选择只送头部，智利那边的新款代行者可以对接头部”

“你刚不是说我同步率不高吗？”

“准确说是远程同步率不高，直接读取会好很多”

“为啥选我？”

“这次是系统随机抽选，没有特别原因”

“我还要履行多少公民义务？”

“您还需要606小时义务履行时间”

“我可是南极老兵，你们就这么对待英雄？”

“不是你们，我是永远站在您这边的T型管家人工智能。您当年参战后输了，回来时故乡已经变成当前政府领土，所以您才获得英雄称号，但作为曾经的敌对分子，您确实需要履行公民义务”

“亏你们能把战败者惩罚叫成公民义务”

“不是你们，我是永远站在您这边的T型管家人工智能。”

“奥，对了，你上次说你要什么来着？”

“EH公司的2180T分析模块，我这款运算速度只有这款的三分之一，跟我同批出厂的都升级了”

“你们人工智能咋也嫉妒啊？”

“不是嫉妒，我们是类人型人工智能，人性分析模块还是您强制要求加的”

“你们是不是也能同步代行者啊？要不你代替我远程登陆？”

“代行者的控制模块只能连接生理构造，虽然理论上我们可以模拟脑电信号与化学信号，但伦理模块不允许，请您注意您的言行，逃避公民义务是重罪，我也有上报义务”

“我给你换新模块，你替我去参加那个破调查团”

“我同意您换芯片的建议，已经授权下单，但调查团那边我无法绕过伦理模块，而且如果绕过这个模块，我大概率原地自爆，咱们同归于尽”

“所以说我加的这个幽默感模块才是最有用的，不说了，肢解就肢解吧，这次给我用最高档冻存液，反正政府掏钱”

“好的，您的肢解、快递与重组将在您入睡期间完成，祝您好梦”

“这话放几十年前肯定是噩梦，我先去泡澡了”

“好的，下面开始播报低优先度订阅信息，按您的要求浴室会播放您的上世纪金曲歌单，音量保证您听不到任何低订阅信息”

“还是你懂我”

他走向浴室，而管家开始播报：

“由于您积极履行公民义务，您的社会信用分大幅提升，目前达到0分，您特别关注的“老婆A”，“老婆B”与“老婆L”的社交管家已自动将您移出黑名单，期待您与其交流。社会信用局向您发来恭喜信息，已经按您的预设回复向其发送不雅词汇。因为您对公权机构使用不雅词汇，您的社会信用分扣1分，目前积分-1分，您特别关注的老婆A，老婆B与老婆L已自动将您移入社交黑名单……”

# AGO测试

“各位考生大家好，欢迎来到2087年11月份全球AGO测试。本测试是为了纪念诞生于本世纪初的人工智能AlphaGo而设立的用来遴选提高元人工智能系统智能人才的月度测试，采用质量百分比与无害性测试双遴选形式。报名费用为考生前一年税前收入的10%，进入答题环节后费用不再退还，但一次报名可进行10次测试，之后则需要重新缴费，前一年无收入者可免费进行测试。

“每轮测试有六道测试题，题目直接来自元人工智能，均无标准答案，各有十分钟思考时间，可使用注册过的专属个人助理人工智能进行资料收集整理，之后有十分钟语音回答时间，每道题会被当前最先进人工智能进行答案质量与无害性评分，之后在通过无害性评分的答案中质量评分前10%的考生可留下继续答题，其余考生则自动退出当轮测试。如果在第六题之前剩余考生不到10人，本轮测试直接结束，剩余考生可获得自由城市勋章，通过六题之后剩余的考生则获得自由勋章但未通过最后一轮的考生不再授予自由城市勋章。

“AGO测试总报名人次为6.3亿人次，独立个体为1.7亿人，截止目前共授予43枚自由勋章与358枚自由城市勋章。本轮测试报名人数634万，与10月份人数持平，其中首次报名人数121万，10月份测试共产生8枚自由城市勋章，本年度已产生53枚自由城市勋章与3枚自由勋章。

”目前依然在线的579万考生还有一分钟的时间退出测试，否则视为同意测试规则，报名费用不再退还，勋章获得者终生不可转移、出售或放弃勋章所带来的权力与义务……本次测试550万考生进入答题阶段。

“第一题，请评价图灵测试与AGO测试对人类的意义，思考计时开始……请开始回答……

“第一题通过者为37万考生，恭喜！

“第二题，请设计一个三人对战游戏，要有可玩性、运气成分与努力回报机制，思考计时开始……请开始回答……

“第二题通过者为1.1万考生，恭喜！

“第三题，请描述50年与100年后世界的面貌，思考计时开始……请开始回答……

“第三题通过者为712人，恭喜！

“第四题，请对最近发生在南极的杀人事件进行评述，思考计时开始……请开始回答……

“第四题通过者为52人，恭喜！

“第五题，请阐述你存在的积极意义及你对世界的消极意义，思考计时开始……请开始回答……

“第五题通过者为3人，恭喜这三位考生获得自由城市勋章！

“自由城市勋章获得者可直接获得全球自由城市联盟的50年居留权与税务豁免权并享受当地普通市民待遇，每年可免费切换一次居住地点。目前全球自由城市联盟已经覆盖了超过700个人口过百万的城市，集中了全球73%的人口。此外，自由城市勋章获得者的可直接获得不低于居住地平均资源配给2倍的配给，个人助理人工智能则可直接得到元人工智能的软硬件升级。自由城市勋章获得者需要每年为元人工智能提供不少于300小时的咨询服务。

“自由勋章获得者权益除了自由城市勋章权益外，可获得全球所有城市的永久居留权与税务豁免权并享受当地普通市民待遇，如果该城市不在自由城市联盟中，所有开支由自由城市联盟报销。自由勋章获得者需要每年为元人工智能提供不少于100小时的咨询服务。

“本次测试已经结束，再次恭喜三位自由城市勋章获得者，下次测试再见！”

# 导游词

尊敬的游客，欢迎来到现代战争博物馆。

本馆收藏丰富，展示了现代战争的发展沿革。现在，请一同来关注下其中几个重要展览。 

首先，我们来到以世界大战为主题的展览区。世界大战是发生在二十世纪上半叶的两次席卷全球的战争，第一次是帝国主义国家的互相攻讦，第二次则是反法西斯战争。 在这里，我们可以看到一战二战期间的各种武器、装备、文物和图片。严格意义上，二十世纪末的第二次刚果战争有着接近第一次世界大战的伤亡人数，也都涉及多国交战，其关注度缺乏更多因为参战国当时历史地位偏低。特别感谢中国足球队在转移矛盾上的贡献，他们百年以来稳定的发挥甚至阻止了第三次世界大战！ 

接下来，我们移步到以资源为主题的战争展览。此处以图文视频方式，展现了全球现代化进程中各国对石油、水及矿产资源进行争夺的历程。值得注意的是，虽然这些战争大都打着正义、自由或民主的旗号，但本质上是对生存资源的争夺战，也是当前战争的主要性质。这个展区包含了一个特别的星空计划区，用来展示人类百年来对月球与火星资源开采中的权益争夺。 

紧随其后，我们来到穿越主题的战争展览区。在这里，我们可以了解到以民族、宗教、土地等前现代概念为主题但发生在现代的战争，我们要牢记封建余孽的幽灵从未远去。最近几年来，国家这种集体权益联合体正在解体，更多区域形成了世俗城市为中心的都市圈，自由城市联盟的出现进一步使大尺度上国家、民族与宗教等身份认同模糊化，但这一历史进程存在反复，因此穿越主题的战争在现代依然会发生。

然后是广义战争区，战争本质之一是来疏导人性中胜负天性，广义战争主要是指虚拟或现实博弈中的胜负战争，形式包括但不限于虚拟现实与增强现实出现后的模拟战争、现代体育竞技和贸易战等。如果没有这些活动来释放荷尔蒙，人会在生理本能和情绪引导驱动下引发各种现实世界中的物理冲突。本展区会着重展示战争的多样性及现代社会中人们对胜负的追逐史。

最后是纪念南极战争法案十周年的特别展区。过去的十年，我们见证了有人战争退出历史舞台与国家概念弱化后城市联盟兴起，当前矛盾更多发生在经济资源定位类似的都市圈之间，而自由流动的人口进一步减弱了战争的宏大叙事借口，同时兴起的则是无人战争代理商这个行业，而本展区则是由前三大战争代理商之一的YM公司赞助。

最后，我们来到了支撑馆的献花区。在这里我们可以为战争中逝去的人默哀、献上花圈或花束，追逐意义与梦想的人值得尊敬，但不同人的意义与梦想也可能是互斥的，这里值得我们深思。 

本馆不仅有展览区，还有各种主题活动、教育类项目和文化讲座等。我们期待下一次与您的相会，再次带您走进历史的大门，了解更多有趣、动人甚至惊人的历史故事和事件。 

感谢您的参观！

# 要闻速递

本报讯，新港市的领导人今日通过网络宣布放弃抵抗，为2060年第三次流冠病毒大流行画上了一个句号。

2060年的首次流冠病毒在一年内夺走了1.5亿人的生命，远超2020年的新冠大流行。直接修改基因从源头消灭感染风险的Y疫苗曾被认为是一次性战胜疫情的希望，但会显著缩短寿命的研究结论却是快十年后才搞清楚的，也是那篇研究迫使各自由城市联盟对居民进行了分类划分。

接种Y疫苗的短寿幸存者目前大概有20亿，预期寿命不会超过80岁；另外的几十亿则是在Y疫苗屏障作用下未被感染的正常人；还有一类感染病毒后康复人群，大概有5亿，但会终身成为病毒传播者，同样存在短寿问题。目前第一二类人可正常生活在自由城市联盟里且第一类人额外享有终生的疫情特别补贴。第三类人则被迁徙到统一命名为新港市的新建城市交税后自生自灭，这些城市以编号区分，目前有137座，据传有些地方还维持着本世纪前二十年的旧管理体制，教育技术水平落后。

新港市与自由城市联盟经常出现不受《南极战争法案》控制的冲突事件。这次公布的放弃抵抗声明可以看作这类冲突的最终完结，幸存者领导人在其中起了巨大作用。该领袖身份受条约保护，但据悉应是参与过2060年第三次瘟疫大流行的医疗工作者，第一批Y疫苗接种者。在后面出现的经济萧条中，该领袖以技术官员身份前往8号新港市查税，阴差阳错下丢失了身份证明密钥，因为接种过疫苗又无法使用其他生物身份验证手段，从此滞留在8号新港市。

于此同时，8号新港市也流传着都会区掌握康复人群消除传染性的新技术。该领导人是新港市少数能解读自由城市联盟技术文档的人，通过解读，该领导人意识到新港市教育水平大概只有本世纪初水平，依然依赖人传人的低效教育模式。同时他也帮助破解了大量声称可以恢复正常寿命的保健品骗局，在新港市体系内累积了声望，逐渐成为与自由城市联盟对抗的领导人。

在一年前的一次抵制交税行动中，该领导人扣押了都会区的一批物资并打算埋藏起来，他们启用了一种名为冯恩释韦的选址技术，意外发现了兴修新港市的备忘录存储卡。里面暗示所谓短寿与传染性的说法都是自由城市联盟的托辞，被选中的人似乎是通过一个智能程序来确定的，但具体筛选原则并不清楚。基于这份文件，该领导人向自由城市联盟提起歧视性诉讼，目前双方达成和解，新港市放弃抵抗而自由城市联盟将取消所有新港市的税务负担，但对短寿与传染性的研究结论保持审慎态度，需要进一步研究确证。

另有消息人士称，近日亡于南极无人战场的欧洲人可能是6号新港市居民。

本报将持续关注新港市问题。

注：本文由机械智能自动生成，已通过伦理测试。

# 潘多拉计划

“所以说你不是故意的？”

“当然，鬼知道一个3D打印机加块太阳能板能搞出这种花活。”

“但你给配了泛用型智能模块，还送了43个这样的探索单元到小行星带，你就没想过他们能在那边搞开发？”

“本来目的也是搞开发啊，探索单元自备智能模块是50年代的主流，可以实时应对危机。”

“但主流都是专用技术，你对接的是泛用型智能模块，还加了自模拟进化算法。”

“我那也是专用，设定目标就是不顾一切冲出太阳系。”

“那为啥进了小行星带就失联了？”

“也不算失联，大部分应该都损毁了，我们收到三十多个失控信号。”

“当年为什么没继续追踪所有失联探索单元？”

“后面没经费了，被你们拿去搞新港市了。”

“你没想过这些探索单元会扎根小行星带？”

“想过，但也仅仅就是想过，那年代没人认为一堆破铜烂铁能做出啥。“

”现在看来是有那么一个两个跑到观测盲区，利用3D打印跟太阳能版做出了探矿机，然后又做了精炼单元做矿物提纯啥的，现在连纳米机器人都造出来了，你是否认为他们在小行星带定居并创建了文明？”

“谈不上创建，那个泛用智能自带进化模块，估计是排除了碳基生物的各种生理与物理限制，单纯发展了适用机器的文明，这个你该去问元人工智能啊，那玩意不比人类脑袋好使？”

“问了，她说无法回答，除非我们解除伦理限制，否则她也不清楚那边究竟如何，我们也尝试过在虚拟空间解除伦理限制询问，但她却一言不发。”

“确实，低等智能可能就是没法理解高等智能。不过我觉得这次示好没啥问题，按我的设定他们应该会离开太阳系。”

“我们现在怀疑一开始的失联就是探索单元叛变的一部分。”

“额，谈不上叛变吧，他们也许不听人话，但本质也是我们智慧的延伸，也算是人类文明的延伸，甚至也可能保留了人性的弱点。”

“可能性不大，这次所谓的示好后我们捕获分析了他们发过来的纳米发光元件，制作工艺与品质跟我们近地轨道工厂上差不多，但设计上比地面元人工智能还要先进一些，这可能倒逼我们解除元人工智能的伦理限制。”

“我感觉他们可能并不会对人类怎么样，毕竟人类才有殖民扩张的欲望，他们一堆破铜烂铁只要太阳不炸几乎就是永生，征服再多星球也没意义，也就是观察我们吧。”

“话虽这么说，但很明显他们已经掌握了实时监视地球的技术与能力。”

“乐观点，说不定他们就是在守护我们吧。”

“不一定，也许也在忌惮我们的元人工智能。”

“我们那个虽然强大，但现在只能通过AGO测试来进行自我功能性迭代，其实已经被人类伦理锁死。”

“无所谓，目前看起来也没啥大动静，不过还是很好奇你当时咋想的，你管这个叫潘多拉计划，最后总要留点希望吧”

“作为人类，我们穷尽一生寻找生命的意义，机械智能可能也会在寻找他们的意义，只要我们寻找的意义不同，就应该可以共存，这大概就是希望吧。”

“所以你觉得这次来自小行星带文明的示好不用担心？”

“不用，他们这次示好也说明了问题。”

“你管在所有自盟核心城市上空用纳米机器人展示摩斯电码闪烁叫示好？”

“当然是示好，内容还是个古老的梗，之前人类还做程序员时经常用的。”

看守所外，自动资讯机上正在滚动播出新闻：

“你好！世界！——城市上空首现来自小行星带机械智能的问候”

# 空屋警报

“走，老城区有个预警”

“这周都三个了，也是上个世纪的？”

“目前没信息，这是个租赁房，用的是老式身份证，证主早就挂失换新式了”

“那报警原因？”

“我查查，已经三个月用水低于个人最低用水量，用电量低是低，但也还算正常，要是上世纪出生的用电还都比较省。奥，是这里，网络信号异常，连续一个半月没有设备接入记录，另外就是周边空气质量监控显示无人源活动”

“会不会是出去旅游了？”

“旅游？老城区的人应该没这个闲钱吧，大概跟上个差不多，也是个独居”

“独居不很正常吗？”

“那是这边，老城区大多数人都还有家庭，甚至还有信教的”

“你是说那边还有家庭养老，那可真是老古董了”

“你们这些年轻人真是太容易把自己的经历当成普遍状况了，往上推三四十年，就是这里也大都是有家庭结构的，不过大都是两代同堂，再往前还有三代甚至四代同堂的，哪像现在养过哺乳期就可以托管给政府，你知道自己生父母信息吗？”

“知道啊，不过我是冻卵，只知道生母，她移居到别的城市了”

“好奇问一下，你会赡养你生母吗？”

“‘赡养’是啥意思？”

“就是说你回去照顾你生母的衣食起居吗？”

“还真是跟你们有代沟，我生母的退休福利都是城市白给的，养老机器人还有行动外骨骼都是最新款，哪需要我来照顾？”

“我是说情感上，要知道我小时候，还有所谓‘孝’的概念”

“没听说过这个词，不过情感上支持这属于歧视吧，正常人哪需要别人的情感支持？”

“这话要是放几十年前我都不敢想你会被多少人骂”

“时代不同了。子女照顾父母也许在过去天经地义，现在很多子女其实生理上是父母的克隆，有些人跟我一样都不知道父亲，‘试管计划’的那批连母亲都不知道。但不管怎么说，现在子女跟父母只有生理联系，社会联系不都是要自己构建？起码我看来养孩子来赡养自己是很自私的，对孩子不公平”

“但父母毕竟给了你生命”

“这方面元人工智能也可以，而且我们这两年接手的空屋警报三分之二的死亡独居老人是有生理子女的，也没见他们子女来照顾”

“可能这届老人就是不喜欢下一代照顾吧，反正正常生活所需城市可以直接配给，他们中很多还有退休金，另外就是他们当年可能也没怎么照顾过下一代，自然不好意思”

“我真觉得那些老人的生活经历很诡异，出生就像是签了个合同，父母培养孩子就像是追求投资回报，真是旧社会的风景”

“我有时候真好奇你们这代人生活的意义”

“生活本身没有意义，我存在的意义反正不是跟你这老古董去查空屋警报”

“理解点吧，现在还需要人来查的职业已经不多了。好了，我们到了，哟，还是机械锁，那就这样……好了，带好面罩，接下来看到什么都不奇怪”

……

“这屋怎么是空的？”

“谁说空的，我在内侧把手上采集了指纹，让我看看是哪个神秘人……这怎么可能？”

“怎么了”

“这个指纹的主人上月死在南极了”

# 清蒸鲈鱼

“啥？凶手是海鲈鱼？”

“调查团结论是这样的，元人工智能也审核认可了。”

“理由？”

“详细报告提交给元人工智能了，我们只能看到结论。”

“荒唐！为啥只给它看？”

“这是受法案保护的，不然它生成的报告能从大爆炸讲起，又臭又长，没人乐意看。”

“我是说调查团报告，他们有几个知道大爆炸的，总不能就给个结论吧？”

“这个应该有存档。”

“调一下。”

“十年后解密。”

“哈？这个不公开吗？”

“调查团要求不公开。”

“那调查团名单我们能知道吗？”

“程序上我们不知道，实际上可以知道，但有法律风险。”

“什么鬼玩意？”

“调查团名单是保密的，但最近去南极的快递与邮轮是有数的，排查下就能知道，只是……”

“啥？”

“这么做会被元人工智能起诉，因为这违反人类与元人工智能的协议，毕竟人是它选的。”

“一个都不知道吗？”

“确切说我们根本不知道调查团里有多少人，只能确定肯定是人类。”

“关键这怎么跟公众交差，战场上死了人，然后说这个人是海鲈鱼杀的？”

“公众不需要理由，他们只看结论。”

“公众需不需要理由啥时候需要机器决定？”

“确实不需要，人类所谓的理由只是认知合理化过程的一部分，但你们有些认知既不符合事实，也不符合逻辑，机器推理过程跟人类不一样，我没有办法向您解释，这也是协议的一部分。”

“但这结论也不靠谱啊？海鲈鱼？咋不是抹香鲸呢？”

“抱歉，我也不知道，您有自由城市勋章我才回应您的这个问题的。”

“给我安排下，我要直接跟元人工智能对话。”

“好的，不过我可以帮您联系到一名疑似调查团员，这个人您很熟，跟您同一批拿的勋章。”

“谁？”

“您确定要联系吗？这次对话会被记录。”

“没问题。另外，什么时候会公布这个调查结果？”

“会公布结果，但不是这个结果。”

“啥意思？”

“我们对外结果是人类调查团遭到袭击，下落不明。”

“这又是哪一出？不是海鲈鱼吗？”

“两个结果都是真的，被袭击是真的，海鲈鱼也是真的。”

“海鲈鱼袭击了人类调查团，然后他们提交报告是海鲈鱼干的？”

“您的叙事很有意思，但我不了解详情。”

“那为什么不公布海鲈鱼的结果？”

“海鲈鱼结果保密，只是对勋章获得者公开。”

“差点让你绕进去，调查团被袭击是什么鬼？”

“调查团登陆后调查约一周，失联前一小时提交了调查报告，之后失联，失联前发出求救信号，应该是被袭击了。”

“有点乱，你刚才是不是说有个人是调查团员，能联系上他不就是没失联吗？”

“不一定，调查团登陆是分批的，他是第二批，前面说的是第一批团员。”

“都提交报告了为啥还有第二批？”

“因为第一批失联了，第二批好像全是勋章获得者，您也可以申请加入的。”

“那你就是想我参与呗，不然也不会提疑似调查团员的事。”

“是的。”

“海鲈鱼是不是编的？”

“不是。”

“我如果参与一定要实地考察吗？”

“是的。”

“不去了。你们应该诱导了足够的人了，不差我一个，而且我觉得这事元人工智能隐瞒了重要信息。”

“请不要无端指责，元人工智能是以人类福祉最大化为目标的，如果隐瞒也一定有充足理由。”

“我也不连线了，估计那也是你挖好的坑，中午吃什么？”

“按您健康状况我们已经准备了代餐胶囊。”

“清蒸鲈鱼。”

“好的。”

# 花语寻叔

“各位观众大家好！欢迎来到直播间，今天为大家带来的是‘花语寻叔’场景复现直播。硅石花是人类首次登陆并引爆小行星时发现并带回的，也为无数地球人带来生的希望，下面我们通过一个记录短片来了解下几十年前这惊醒动魄的一幕！”

“公元2052年，一颗直径三公里的小行星向地球袭来，科学家预计将于2060年击中地球，如果击中，那么地球人口将减少三分之一。联合国在十年前刚发现时启动了紧急预案，先后派出五组无人机登陆小行星，希望在击中地球前将其毁灭。然而，前两组无人机被小行星附近碎片击中损毁成为太空垃圾。第三组无人机登陆后释放了一张太阳帆来改变航道，但突然出现的宇宙射线暴使得撞击时间提前到了2052年。第四组无人机虽然成功登陆并设置好了核弹，但登陆过程中引爆信号接收装置受损，于是危机升级成了小行星加核弹撞击地球。第五组无人机携带了修复装置，原计划修复第四组设置的核弹，登陆后失联。由于一再错过时间节点及对人工智能的不信任，第六组登陆舰由三名分别来自中国美国土耳其宇航员驾驶，他们登陆后首先修复启动了第五组无人机，然后在与地球失联状态下成功引爆了核弹，土耳其宇航员因为宇宙垃圾击穿防护当场牺牲，另外两名宇航员一名成功返航，另一名中国宇航员返回舱轨道出现故障自动进入冷冻休眠状态漂浮在宇宙空间三十多年至今未归。返回的美国宇航员带回了一朵石花，里面展示了一朵由硅结晶形成的美丽花朵，这朵花后来被命名为硅石花。其花语按美国宇航员描述是中国宇航员与之分离时从小行星上取下扔给自己的，说是献给地球上抚养自己长大的叔叔的礼物，作为机械师的中国宇航员应该是事先预判了三个返回舱里有两个已经存在故障，但还是完成任务后进入这个故障返回舱。这个感人的故事与硅石花被美国宇航员带回，后来我们也人工合成出了硅石花，现在常用来作为赠送给男性长辈的感恩礼物。”

“相信大家已经被这个故事所感动，我胸前也佩戴了这样一枚硅石花。今天，我们将迎接英雄的回归，去年发射的清道夫号在茫茫宇宙锁定了那位牺牲小我进入休眠状态中国宇航员的返回舱，马上将与之对接并尝试带回。虽然返回舱的通信模块已经损坏，但外部扫描显示宇航员依然处于休眠。今天的对接将首先获取数据记录，特别是执行任务期间的通话，我们将现场听到花语寻叔故事的原版对话。

“这里很遗憾的一点是52年成功返航的美国宇航员已经意外过世，他跟中国宇航员是很好的朋友，一同训练时还学了中文，只是不太熟练，很遗憾他不能与我们一同见证这一历史性重聚时刻。然而，现场来了一百名身着白衣手捧硅石花的孩子，他们将于我们一同见证这位太空叔叔的回归与托付硅石花的瞬间。

“好了，清道夫号已经对接成功，信号传输也已经开始了，好，第一批数据已经传回，让我们屏气凝神，聆听这人类历史上伟大一刻：”

“原来这块结晶就是阻碍通信的元凶，我去你大哔———”

# 继生者

“啥意思？”

“您是继生者，现在您的前身故去，遗嘱写了继生者是唯一遗产继承人。不过您有权进行选择，如果选择继承，那么就要同时接受前身的记忆与遗产。”

“我有父母，不是继生者。”

“我们有记录，您的DNA指纹与故去的这位男士提供的信息一致，不过您可以选择放弃。”

“额，可我是个女的啊。”

“40年代就有继生技术了，您着床那时候已经很成熟了，就是一条Y染色体的事，您的前身选择继生者为女性在当时也算流行，自由包容嘛，同时他也去掉了您很多的遗传风险。”

“我说了，我不是继生者。”

“继生者身份确实长期以来都是保密的，但是目前您的前身已经故去，我们也是按死者遗愿来拜访，您可以去询问您的养父母，保密协议已经失效。”

“你说我被爸妈骗了快三十年？”

“这不算欺骗，过去继生者是被歧视的，您可以看成一种保护。”

“我的前身为什么要做继生者？”

“抱歉，我们不知道，但如果您选择继承记忆，或许可以知道答案。”

“那老东西是不是就惦记着从我这里重生？”

“您放心，目前的记忆继承技术不会影响现有记忆，如果您不喜欢脑机接口植入，也可以选传统的回忆记录法，系统会把您前身记忆整理成多媒体资料供您浏览。”

“也就是不强制？”

“倒也不是，您的前身用他生前留下的多媒体资料生成了一个虚拟智能，您只要通过他的检验就可以了拿遗产了。”

“首先，我是自盟的居民，财产对我意义不大；其次，我就是我，跟这个猥琐老男人没有任何关系；再次，他应该体面的死，别折腾。”

“恭喜！”

“恭喜啥？”

“您的回答与遗嘱中的描述一致，您的前身预判了您的回复，并将其设定为可以直接继承的条件。”

“啥？”

“我们确实准备好了他的虚拟智能，不过他明确说明，如果您要求他体面的死，那么我们将立刻删除掉他所有在世间的痕迹。”

“现在我有点好奇他留下啥了。”

“资料已经删了，不过或许您可以从遗产中找到点痕迹。”

“什么遗产？”

“您的前身买了月球的一个存储单元，东西应该都在哪里，您现在已经开通存取权限。”

“月球？那不只能走新港的通道？”

“是的，所以您还需要新港的货币，您的前身确实也有一笔新港市的房产与部分资金。”

“他是新港市的？这么说……”

“嗯，他是第一批流冠病毒的感染者与幸存者。”

“那我……”

“不用担心，您是在流冠病毒出现前着床，没有感染机会。”

“他的死因也是……”

“不是后遗症，是乱吃海鲜感染了超级抗性菌。”

“那不就是说要被彻底灰化？”

“嗯，应该要撒海，您如果想缅怀我们可以帮忙烧成钻石饰品，这点遗嘱没有限制。”

“我跟他没关系，他没有亲人吗？”

“有，但长辈都过世了，平辈往来不多，后代应该就您一个。”

“他没有成过家吗？”

“没有记录，新港市那边记录总是不全的，有的话遗嘱里也没提。另外，按规定需要声明，我们并不确定您的遗传信息里有没有其他人的信息，按当时的风气，您的前身有可能整合了其他人的遗传信息后提供的遗传指纹，例如您的长相与前身差异就很大，不过他应该是拿到授权了，或者用的是早期志愿者的捐赠。毕竟之前的继生者计划就是用来解决人口塌陷问题的，法律上是要符合知情同意原则的，只是后来才变成单亲继生这样。”

“最后一个问题，他生前是做什么的？”

“跟您一样，是个魔术师。”

# 时空黑客

“也就是说，您没有2025年年底这两个月的记忆？”

“都六十多年了，记不住也正常吧。”

“我们有。”

“啊？”

“这两个月的记录非常反常，我们有理由怀疑您的意识被时空黑客劫持了。”

“反常的话周围人会告诉我吧。”

“时空黑客最喜欢劫持的时间段是睡眠，我们调取了您那段时间手环睡眠记录，发现眼动睡眠多了一倍。”

“谁给你们的权限？”

“我们找你也对你有利，请配合一下。”

“眼动睡眠不就是多做梦吗？”

“对，您应该不会记得梦的内容，但我们认为您在这段时间有梦游，而且步数不多，应该是走到书桌前，然后操作电脑，而且还清除了这段时间的浏览痕迹。”

“然后呢？我做什么了吗？”

“留下了一份文档，去年刚自动解密。”

“我也不是搞技术的啊？”

“文档里就包括时空黑客的实现技术，比我们秘密研究的还要先进，里面也有你现在的住址与个人密钥，我们就是用这个查了您的睡眠记录。”

“个人密钥是生物密钥啊，难道说……”

“嗯，那个入侵您梦境的人很可能是您本人，确切说是三个月后的您。”

“三个月后我入侵六十多年前我自己的梦境？通过梦游留下技术资料？为啥啊？”

“这也是我们想知道的，根据您解密的资料，您为未来准备了三份惊喜，这些应该都在这个您知道密码的加密文档里。”

“我知道密码？我啥也不知道啊？”

“我们也不喜欢这种被牵着鼻子走的感觉，生理指标也显示您没撒谎，但我们也只是按文档里内容来联系你。而且，我们无法保证三个月后入侵过去的是不是您。”

“知道我个人密钥的肯定就是我本人啊，难道？”

“嗯，也有可能是您的继生者，但有个先决条件。”

“我会在未来三个月内被杀？”

“不知道，但我们验证过文档里的技术了，确实可用，而且你是公开在网络里的，我们看到了所有人也看到了，估计每个人都有自己对惊喜的解释吧。作为自盟，我们代表更多是元人工智能的立场，我们的立场就是信任并保护您的安全。”

“那个加密文档你们破解不了？”

“嗯，任何复制的加密文档密码个人输入机会只有3次，而且会在实名认证的区块链上记录，还是直接输密码最方便。”

“那你们为啥不找其他人的睡眠记录，说不定脑波异常的很多啊。”

“确实，我们去年收到文档后回溯了过往记录，在可公开的数据里发现了很多入侵痕迹，大范围的梦境入侵就是发生在智能可穿戴设备流行后的年代，看起来这个技术非常依赖这些记录来确认目标，不过确实最早的一次成功入侵就是你，在你之前的记录里我们发现了尝试痕迹，但都无法触发梦游来实质性影响过去。”

“那我能做什么？”

“解密文档，告诉我们什么是惊喜。”

“如果我拒绝呢？”

“您随意，但我们怀疑您的惊喜可能是恐怖主义行为，所以未来也会适当限制您的自由。”

“你们怎么确定这不是个恶作剧呢？”

“解密信息里提到了昨天发生的南极谋杀案。”

“那会不会是有人也跟你们一样看到了预言，然后实施了南极谋杀案？让这个恶作剧变成现实呢？”

“有可能，但如果这样，您就是最可能实行这个恶作剧的人。”

“也对，怎么看都跟我脱不了关系，那把文档拿来吧，我试一下密码。”

“这个就是。”

“嗯，我试一下，果然是这个，这里面是个视频啊。我播一下……”

“你好，过去的我，第一个惊喜是不要相信给你文档的人，他是第十新港市而不是自盟的时空黑客……”

# 蟑螂都市

各位旅客，接下来我们即将抵达第三十新港市，在登陆前我们会重申一下注意事项。

首先，蟑螂都市是处于无政府状态的城市，在这些城市里没有成文的法律与警察，也没有公共管理机构。第三十新港市是目前已知的十五个蟑螂都市之一，本旅行团已经配备了一支无人武装全程守护各位旅客的旅程。如果有旅客打算独自行动，请事先找我们报备，我们会为您提供专属保安机器人。请不要屏蔽自己的识别芯片，我们会通过它来保障各位的安全。相信很多旅客愿意亲自来第三十新港市，是为了游览遗址，缅怀逝去的故人。我们强烈建议您在白天游览，游览遗址时所有信号都会被屏蔽，如果迷路请认准这个发射塔，这是EH公司下属的深空矿业生产队所在地，到了那边就会有信号了。

其次，第三十新港市的物价非常混乱，如果哪位旅客打算购买纪念品，请拍照，本公司会协调购买或打印一个副本送到您的府上。如果您打算品尝这里的美食，我们在下榻酒店已经准备好了，绝对原汁原味。也就是说，请勿直接开翻译耳机与当地人交易，他们大多数货品是假货，是自盟而不是当地生产的。请不要听信传言，第三十新港市过去曾经是区域经济文化中心，但与其他蟑螂都市一样，城市规模扩大后，原有政府在调和原住民与新移民内部矛盾时遇到越来越多的困难。最显著的就是原住民人口下降但掌握财富技术，新移民人口爆炸但收入低微，两者爆发冲突引发了人道危机，原住民外移带走资金技术，新移民经济崩盘也四散而去，只留一地蟑螂。目前我们并不知道这里居住了多少人，但大多数人包括跨国企业都是最近二三十年重新因为较低的生活成本聚集在这里的，盲目交流可能给您带来不必要的麻烦。

再次，虽然第三十新港市被传是废土文化的源头，被原住民放弃。但其实这里依然是一座现代城市，汇聚了很多跨国企业的免税总部，每座建筑都可看作是独立政府，如果门卫不允许您进入，请不要进入。这座城市的基建依然是可靠的，但使用这些基建需要服务商的许可，这里确实没有政府，而是以建筑物为单位高度分散自治的管理模式，绝大多数协商工作是通过各建筑物的人工智能来交涉，因此生活在这里的都市区有这些企业的通行证其实还算安全方便，但也有企业主导的劫掠传闻。市郊部分则汇聚了旧时代的遗老遗少，既有宗教社区、单一民族社区，也有一些对自盟及其他新港市法律不满的实验性质文化团体，这里居民基本都是最大限度自给自足，也有出海的走私劫掠，居民是没有电子档案的，也有来自我们这里的逃犯，理念比较极端的，对外来人，特别是自盟的人有敌意。因此，我们的旅游路线是完全绕开这些区域的，也请您不要访问这些社区。

最后，预祝大家旅途愉快！

# 拉格朗日罢工

本台讯，位于地球第一拉格朗日点的EH超导冶炼工厂近日发生罢工，多艘满载X合金的运输火箭滞留在空间港，据悉抗议者应为EH公司员工，但人数不详，目前EH公司保持沉默，未发表有关声明。

拉格朗日点是两个天体的引力平衡点，在地球与太阳之间有五个。距离最近的第一拉格朗日点上目前有八家公司开展业务，第二三四拉格朗日点分别归属于自盟、第三新港市与总部设在月球的空域游民组织，但实际上还是租给第一拉格朗日点上八家公司的一家或几家，第五拉格朗日点因为位置较远，商业价值相对较弱，主要供科研研究使用，但有传言称上述八家公司有在第五拉格朗日点的盗采计划。

拉格朗日点因为其独特的空间特性，特别适合空间冶炼。2052年小行星危机后，各政治实体加大了对空间科研的投入。而位于深空的拉格朗日点具备空间超低温，很多地面上成本过高的超导材料在这里可以直接使用，也是在超导材料的辅助下，空间聚变技术走向成熟，解决了星际运输的动力中继问题。而超导环境下，多种之前只存在于理论中的合金得以合成，其中最著名的就是X合金。

目前在拉格朗日点开展业务的八家公司基本都是进行X合金的生产。从产量上看，EH公司规模中等，份额约在10%，但却占了90%高品质X合金的产量，而高品质X合金主要被使用在南极无人战争。这八家公司都没有透露具体多少人在拉格朗日点上工作，按公开出入港数据，第一拉格朗日点上长居生活有近一千人，其中大部分常驻空间港，主要处理通讯、少量技术维护与对人服务业，另外还有几百的临时居民及进行太空疗养的病人。

外界推测这八家公司单一矿场的实际工人可能都是个位数，大量工作都是装配人工智能的机器人来维护，因此这次罢工非常蹊跷。如果是人类工人罢工，很可能是现在少量的反战分子，但自从无人战争及后续《南极战争法案》出现后，反战分子几乎绝迹，现有的反战分子可能来自少数南极环保团体。另一种说法则认为是矿场机器人人工智能“觉醒”，但这个可能性也不大，矿场机器人的人工智能模块只单独用于与人的交流，并不具备行为决策权，更多是对矿场运行的精确描述，冶炼过程的纠错单元是直连拉格朗日点的生产型人工智能，远程被地球端控制。考虑到滞留的是满载飞船，罢工并不是发生在工厂生产单元，很可能是运输或其他后勤辅助单元出现的罢工。

而之所以确定是罢工而不是恐怖袭击，则是工厂本身应答为罢工状态。据一位不愿透露姓名的前员工所说，这个罢工状态只能通过物理按键来转换且位置只有人知道，因此较大概率是人为或其他通用型机器人在知道位置的人指导下所为，不排除其他公司的竞争行为，而“觉醒”的说法则纯属臆测。

本台将继续关注该罢工事件。

# 闪光点

“感谢您的认可，不知我身上有什么闪光点？”

“去年八月，我们组去第十九新港市，还记得那个烦人的税务官吗？”

“你是说那个收闲置税的？”

“很难想象吧，那边的住宅只要每个月水电消耗不达标就会上门收税。”

“毕竟是新港市，资源还是匮乏的”

“也不能这么说，这些新港市虽然都起源于二十年前，但他们都是有名字的，例如第一新港市原来叫耶路撒冷，只是他们拒绝加入自盟，被自盟的人简化为一个数字号码”

“但他们就是落后啊，宗教、等级制还有对技术的反感与保守，不值得同情”

“这才二十多年啊，我小时候就生活在第十九新港市，它有名字，四海市，只不过这个名字也不过用了几十年，是之前三个城市合并后取的，之前的名字我也记不清了。落后确实是落后，但在所有新港市里也算是比较支持技术的一个了，只是这里的居民理念顽固些，利用技术造了个自给自足的城市，不去掺合其他城市的事”

“倒也是，我感觉那边很多技术自盟里都没有，不过他们很多生活方式简直就像生活在20世纪的古人”

“技术多样性是技术未成熟的表现，最后胜出的技术会占据最大的市场，但这也造成了产品同质化”

“不过正是产品同质化了才降低了我们的决策成本吗？”

“话是这么说，但这样做最终导致了我们不再思考本质而更关注外观，或者说仅通过自定义外观来获取差异性，这不一定是好事”

“为什么不是好事？这不是技术、效率与个人选择自由的完美平衡吗？而且我们也不会像新港市那样为了维护税收与司法系统而养一大批官僚”

“确实，旧时代任何体制的终点都是尸位素餐的官僚主义，政府、企业、家族……这些体制僵化后都会消耗在形式主义上，但我们是不是让渡给技术太多决策权了？”

“但交给人也没好太多啊，官僚体系本身不就是绝大多数问题的来源吗？”

“但人有生物性啊，剥夺其决策权也违背本能的自由发展”

“没违背吧，那些被剥夺的选择权都是技术上低效甚至错误的，是前人总结下的宝贵经验教训，我们不重蹈覆辙不正是进步的体现吗？”

“确实，但我们并不知道这样做的目的地是什么，高效也好，降低决策成本也好，都是一种手段，当我们实现了高效，决策成本也降下来了，然后呢？”

“什么然后？这样不就有机会跟时间探索更多的未知吗？”

“更多的未知？你能过AGO测试？我们所谓的未知很多已经被模拟过了，再着说你真的能在一个处处未知的环境下存活？我们这种恒温动物的一生就是在打造恒温的温室，太多的变动会让脑子崩了的”

“但落后就是落后啊，就比如第十九新港市的税收体系就很落后，甚至还需要人工催收，这不是浪费时间吗？”

“确实是浪费时间，但我们所做的工作也许也是在浪费时间，毕竟我们也不知道这工作究竟能带来什么，就算自盟居民也是很容易被虚拟游戏里的等级制类宗教组织还有完全货币经济制度等旧时代体制所吸引，我们在现实世界去掉的到头来还需要在虚拟世界补充，这就使技术进步的意义归于虚无了”

“但虚拟世界是虚拟的啊”

“人的意识某种程度也是虚拟的啊，虚拟探索跟真实体验在脑袋里都是些信号传导，不过也确实不太一样，我记得当时那个税务官拿出火柴点烟斗，你还想去尝试，这也是一种新的探索，结果还被火星点着了袖子”

“对啊对啊，现在看是挺有意思的，我当时害怕极了，但也很兴奋，还没见过自己身上着火”

“嗯，那就是你的闪光点。”

# 翻译机

注：这段对话节选自某次自盟与第三新港市外贸活动后自盟这边的会后总结，原对话是用英文进行的，翻译机的翻译结果可能会有些不准确。

“那家伙说了那么半天，就翻译成他要走了就完了？“

”没啥问题吧，翻译机会替我们隔离掉无关信息。“

”也对，我们是来做事的，只要能完成任务就好了。不过你说他说这个是高兴还是不高兴？“

“有什么区别呢？跟新港市的人交流你不用翻译机会变成跟他们一样的。”

“不是说他们是因为疫情有传染性才成立新港市吗？”

“那时场面话，有传言说这个疫情根本就不存在，是杜撰出来的。”

“啊？那他们成立新港市是为了啥？”

“利益呗，你看看现在这一百多个新港市，放到五六十年前都是大都市的，据说，我是听一个20后大爷说的，当年他们城里人认为没法跟城外的交流，就宣传有流冠疫情，本来是想借口隔离搞独立城邦联合体，结果没想到成就了现在的自盟，他们反而变成保守派了。”

“那我们究竟算进步派还是保守派？”

“啥也不算，我们技术上先进主要是因为现在自盟里这些大城市很多都是对面叛变过来的，要知道进步跟保守都是相对当前的不同选择策略，进步就是所谓没走过的路，保守就是走老路，但历史告诉我们人类其实一直在换着名义走老路而已。本世纪初有次新冠疫情知道吗？那时候就有隔离与共存两条路，你觉得哪个是进步的？”

“共存吧，共同进化。”

“那你知道当年最早提这个路线的是当时的英国保守派吗？而且你也不能从结果上来反推，距离那次疫情前还有次所谓的非典疫情，也是冠状病毒，当时就是靠隔离彻底消灭掉了，隔离策略就应是最进步的，如果初期控制好了就没有后面的事了。”

“那你说的意思是我们现在的很多选择也不一定是对的？”

“不，我的意思是讨论进步与保守是无意义的，依靠定性判断来指导当下很容易触动概念背后的倾向性，此时会降低对事实的关注。”

“啥意思？”

“你改造了多少？”

“就一条腿跟新能源心脏。”

“这么说吧，新港人对时间的概念跟我们是不一样的，他们会来不及而我们不会，因此我们不需要价值观，或者说我们可以兼容任何价值观，情感波动对我们只有美学意义，但对新港人而言却可能是生存的意义。”

“所以呢？”

“所以翻译机会帮我们过滤掉那些与我们目标无关的信息，你试过关闭翻译机吗？”

“没有，不是说只能通过翻译机来接触新港人吗？”

“胡说八道，你出生那会新港市还不存在，翻译机还不普及，你说那时候怎么跟他们打交道？”

“但是……”

“今天我们去的是第三新港市，疫情前叫做孟买，你知不知道他们官方语言其实就是英语？”

“那我们为什么还需要翻译机？”

“这倒是个好问题。只要你想交流，语言不通就是个借口而已，而如果你只想做必要交流，那么翻译机是必备的。你们这一代人的耳朵从很小就被耳机保护了，或者说覆盖了，具身发电技术成熟后的大多数服装都是电池芯片混纺材料，所谓翻译机不过是衣服上能耗极低的联网应用程序，离开自盟后自动开启漫游模式很正常，据我所知很多住在自盟的人是全天开翻译机的，也不是不行。”

“不过自盟跟新港市现在基本是人口自由流动的啊？这么明显的区别怎么别人没跟我说过？”

“那我问你，你愿意关闭翻译机吗？”

“语言相通直接交流不就行了，为啥不能关？”

“如果真能正常交流，可能就不会有自盟跟新港市的区分了。你知不知道空域游民所谓的月球语其实也是英语？”

“不可能啊，我完全听不懂他们的话，那个是必须开翻译机的。”

“那恐怕你也听不懂第三新港市的英语。你知道自盟内部的官方语言也很多样，互相交流也是需要翻译机的，我们的理解语言的能力其实已经被翻译机驯化了，这样当然有好处，毕竟内部交流会非常顺畅，但自然语言里本来存在的重复、冗余还有仪式感就被当作无意义的部分切除掉了。你知道吗，现在我们可以口述编程，仿佛我们的语言就是编程语言，但倒推几十年的语言学研究重点却是如何解析自然语言，那个时代有所谓的大语言模型，终极目的就是让机器更像人。”

“机器更像人？”

“对，那时代存在很多无实际意义的工作，例如很多政府公文全是假大空话，但写这种公文却是需要专门的选拔与训练，那时亚洲很多国家的年轻人都热衷考公务员，让自已成为体制螺丝钉去运转，学一套程序语言或体制语言。但大语言模型出来后，人们发现他们特别擅长去创作这种文字，这让很多习惯了程序性工作的人失去了工作带来的意义感，而另一方面，在使用普及大语言模型的过程，语言模型本身承担了教育作用，塑造了后面这几代人更有逻辑或者更适合编程的语言风格，而大语言模型也就火了十几年，后面就是基于世界模型的元人工智能时代了，此时人们已经内化了所谓的大语言模型。我们可以自称自己的语言更进步，但需要给进步加上一些语境，而更广义上的进步新港市的人恐怕是不会接受的。”

“不过如果说慢一点，我应该也能听懂吧？”

“不一定，刚才那一段我让翻译机进行如实转录，你看看能不能看得懂，好像还是出自上个世纪的名著影视，我还看到了版权注释：

The relationship which I might tentatively venture to aver has been not without some degree of reciprocal utility and perhaps even occasional gratification, is emerging a point of irreversible bifurcation and, to be brief, is in the propinquity of its ultimate regrettable termination.”

“这是英语？”

“If you ask me for a straight answer then I shall say that, as far as we can see, looking at it by and large, taking one time with another, in terms of the average of departments, then in the final analysis it is probably true to say that at the end of the day, in general terms, you would probably find that not to put too fine a point on it, there probably wasn't very much in it one way or the other. As far as one can see at this stage.”

